Init config before service start
registering options during oslo.service start can result in a race with
oslo.service's own startup logging of options, producing error

RuntimeError: dictionary changed size during iteration

Groups found to be responsible are [ssl] (from oslo_service.sslutils)
and [keystone_authtoken] (from keystonemiddleware.auth_token).

This was cought when starting designate-api with `--log-config-append`
option with extra logging config containing many handlers
(some are heavier to init than others, like fluentd),
thus introducing enough time lapse for race to surface.

Change-Id: I2295d91077b5cdc905eafa6f24a7b73168ceb1aa